### PR TITLE
feat: new description on pose_ref_index

### PR DESCRIPTION
**Pull request by nathan-vm**
- [x] refactor on DynamicForms 
- [x] closes: #12

### CODE REVIEW

**Comment by garrettmflynn** [comment]
@katiekly Can you confirm these are the same across all data that will be loaded into VAME?

**Comment by garrettmflynn** [comment]
@nathan-vm Thanks for covering this! I forget if I've written in the min/max logic into the number inputs.

Can you confirm and add if this is missing in the DynamicForm?

**Comment by nathan-vm** [comment]
> @nathan-vm Thanks for covering this! I forget if I've written in the min/max logic into the number inputs.
> 
> Can you confirm and add if this is missing in the DynamicForm?

@garrettmflynn It is not covered but i can manage do tha in this PR allready 

I can handle this recursively or simply copy the base inputs to another file and have a check in the DynamicForm:

```javascript
 isArray? <ArrayItemWrapper>.map(i => <BaseInput/>) </ArrayItemWrapper> : <BaseInput/>
 ```

**Comment by katiekly** [comment]
Hi @garrettmflynn, yes all body parts should be the same for each CSV loaded.

**Comment by garrettmflynn** [comment]
@katiekly Sorry what I meant is are these the same **across Projects**? Just want to confirm that specific property of the CSV files.

**Comment by garrettmflynn** [comment]
@nathan-vm Whichever you think is best! Seems like it might be more appropriate to break the input generation out to a component of its own

**Comment by katiekly** [comment]
@garrettmflynn, thanks for clarifying. No, the CSVs column header may vary between Projects. Some projects would require different annotation points, which defines the CSV column headers.

**Comment by garrettmflynn** [comment]
@nathan-vm So Katie's last comment means that this cannot just be a description in the `json` file, but would have to be dynamically loaded into the project and injected into the schema. Still much easier than I was originally thinking!

Also not sure about your availability, but we're meeting in an hour if you'd like to join. I'll introduce you to the client.

**Comment by nathan-vm** [comment]
@katiekly I think what I did here work just fine, @garrettmflynn how can I send to her for testing it before I merge it ?

**Comment by garrettmflynn** [comment]
Katie should be able to pull this branch and try it out!

**Pull request merged**
